version: '3'

services:
  app:
    build: .
    environment:
      FLASK_APP: wtex.application
      FLASK_ENV: docker
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    networks:
      - watchtower_default
    command: flask run --host 0.0.0.0 --port 5001

networks:
  watchtower_default:
    external: true